### ISSUE TITLE
Add *.md to selected file extensions to support rubocop-md checks

### ISSUE THREAD

**Issue by rubyconvict** [dukaev/rubocop-changed#4]
I find this rubocop extension very helpful: https://github.com/rubocop/rubocop-md, but it seems that it cannot be used together with `rubocop-changed`, because it only selects `*.rb` files from the diff.

**Comment by dukaev** [comment]
Hello, Marcin!
Thank you! Let's add this`.md` too.

**Comment by rubyconvict** [comment]
Sorry, somehow I was looking at the code of a different gem with almost identical name. This one works great!
