### ISSUE TITLE
Error when RUBOCOP_CHANGED_BRANCH_NAME not set

### ISSUE THREAD

**Issue by rubyconvict** [dukaev/rubocop-changed#5]
I have this error when RUBOCOP_CHANGED_BRANCH_NAME is not set, but it seems like it should not be required (https://github.com/dukaev/rubocop-changed?tab=readme-ov-file#additionally). It looks like the default base branch checking command is not working. I have the same issue on my Mac and on Ubuntu in Github Action. I googled for an answer and found some idea to run `git gc`, but I run this on a very "young" repo, so it looks like some nonsense. Perhaps, it's related to `git` version. Maybe it would be a good time to update the default command to something like: `git remote show origin | sed -n '/HEAD branch/s/.*: //p'` - I know, not perfect. Optimally, readme could be updated: https://github.com/dukaev/rubocop-changed/blob/51b5b8850be41ec505e109733f3d5d85d7e754c6/README.md#additionally.

```sh
$ bundle exec rubocop --require rubocop-changed
Unknown error. Please, create issue on https://github.com/dukaev/rubocop-changed/issues.
Command:
git symbolic-ref refs/remotes/origin/HEAD
Output:
fatal: ref refs/remotes/origin/HEAD is not a symbolic ref

$ cat .git/refs/remotes/origin/HEAD
cat: .git/refs/remotes/origin/HEAD: No such file or directory
```

**Comment by dukaev** [comment]
Thank you! I like your idea 🔥
Could you please open PR?
